name: 02 - Runners
on:
  # push:
  #   branches: [main]
  workflow_dispatch:
jobs:
  ubuntu-echo: 
    runs-on: ubuntu-latest
    steps:
      - name: Show OS
        run: |
          echo "Running on a Ubuntu runner"
          echo $RUNNER_OS
  windows-echo: 
    runs-on: windows-latest
    steps:
      - name: Show OS
        shell: bash
        run: |
          echo "Running on a Windows runner"
          echo $RUNNER_OS
  macos-echo: 
    runs-on: macos-latest
    steps:
      - name: Show OS
        run: |
          echo "Running on a Windows runner"
          echo $RUNNER_OS
